name: Publish Workers-Types Site Workflow

on:
  push:
    branches:
    - main
  schedule:
  - cron: '25 4,12,20 * * *'

concurrency:
  group: workers-types
  cancel-in-progress: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: false
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: pnpm/action-setup@v4
      with:
        version: 8
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        cache: pnpm
        node-version: 20
    - run: pnpm install
    - run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: read
      deployments: write
    #needs:
    #- lint

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        cache: pnpm
        node-version: 20
    - run: pnpm install
    - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
      with:
        key: tarballs
        path: src/tarballs
    - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
      with:
        key: astro
        path: node_modules/.astro
    - run: pnpm generate
    - run: pnpm build
    - uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
      with:
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        directory: dist
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        projectName: workers-types
