name: Publish Workers-Types Site Workflow

on:
  push:
    branches:
    - main
  schedule:
  - cron: '25 4,12,20 * * *'

concurrency:
  group: workers-types
  cancel-in-progress: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: false
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 20
    - run: pnpm install
    - run: pnpm lint
  
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      deployments: write
    #needs:
    #- lint
    
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 20
    - run: pnpm install
    - uses: actions/cache@v3
      with:
        key: tarballs
        path: src/tarballs
    - uses: actions/cache@v3
      with:
        key: astro
        path: node_modules/.astro
    - run: pnpm generate
    - run: pnpm build
    - uses: cloudflare/pages-action@v1
      with:
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        directory: dist
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        projectName: workers-types
