name: Publish Workers-Types Site Workflow

on:
  push:
    branches:
    - main
  schedule:
  - cron: '25 4,12,20 * * *'

concurrency:
  group: workers-types
  cancel-in-progress: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: false
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        cache: pnpm
        node-version: 22
    - run: pnpm install
    - run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: read
      deployments: write
    #needs:
    #- lint

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        cache: pnpm
        node-version: 22
    - run: pnpm install
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        key: tarballs
        path: src/tarballs
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        key: astro
        path: node_modules/.astro
    - run: pnpm generate
    - run: pnpm build
    - uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
      with:
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        directory: dist
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        projectName: workers-types
